### ISSUE TITLE
How to get uppercase description via macro?

### ISSUE THREAD

**Issue by minthemiddle** [BenSampo/laravel-enum#114]
I try to extend the Enum class with a simple `getDescriptionUppercase` method that returns the uppecase version of the description.

I tried to simply add it to `AppServiceProvider` like the following but don't get which parameter I have to pass to `getDescription()` which requires one argument:

```php
Enum::macro('getDescriptionUppercase', function() {
  return strtoupper(self::getDescription(??));
});
```

I tried `$this->status` which is the enum field for the description, but obviously, `this` is wrong in the service provider.

How can I add this generic method?

**Comment by BenSampo** [comment]
The `getDescription` method takes the enum value as a parameter so you'll have to pass that into your macro function too. e.g.

```php
Enum::macro('getDescriptionUppercase', function($value) {
  return strtoupper(self::getDescription($value));
});
```

Then use it like so:

```php
UserType::getDescriptionUppercase(UserType::SuperAdministrator);
```

**Comment by wessRay** [comment]
Hi @BenSampo , thank you for creating this awesome package.
May I know what's the reason that we should use macro to extend the enum functions, instead of using static functions?
Because I found we can simply add a static function named "getDescriptionUppercase" to `UserType` class, and it basically achieve the same output.
