### ISSUE TITLE
v1.36 update made wrong laravel/nova locale.

### ISSUE THREAD

**Issue by bolechen** [BenSampo/laravel-enum#136]
Sorry, it's be inconceivable bug I can't understand why. 

I'm `laravel/nova` user, today i update laravel-enum from v1.3.5 -> 1.3.6,  when i visit nova admin url, the locale translate string is all gone.

![image](https://user-images.githubusercontent.com/195015/77521208-442e9800-6ebd-11ea-97e3-aa621e2b94d4.png)

 I try downgrade this package use 

```
composer require bensampo/laravel-enum:1.35
```

and it resume normal.

![image](https://user-images.githubusercontent.com/195015/77521368-89eb6080-6ebd-11ea-8efd-7d6c70548c77.png)

The nova locale doc link: https://nova.laravel.com/docs/3.0/customization/localization.html#overview

**Comment by BenSampo** [comment]
Did you get to the bottom of this?

Some translations for validation rules were added between 1.35 and 1.36, but it shouldn't interfere with other packages.

https://github.com/BenSampo/laravel-enum/compare/v1.35...v1.36

**Comment by bolechen** [comment]
> Did you get to the bottom of this?
> 
> Some translations for validation rules were added between 1.35 and 1.36, but it shouldn't interfere with other packages.
> 
> [v1.35...v1.36](https://github.com/BenSampo/laravel-enum/compare/v1.35...v1.36)

I change the `bootValidators` method, and the issue is gone. see the  PR for detail.

**Comment by cweiske** [comment]
This is the same issue as https://github.com/msurguy/Honeypot/issues/64 - see there for a truckload of other linked issues.

`BenSampo\Enum\EnumServiceProvider` is booted very early, and already uses the translator.
`Laravel\Nova\NovaServiceProvider` is booted later and adds additional configuration to the translator.
Unfortunately, the translator has already loaded its configuration because of `EnumServiceProvider`, and thus ignores the "new" configuration provided by Nova.

When `EnumServiceProvider` does not use the translator, everything is fine.
