### ISSUE TITLE
next major version ideas

### ISSUE THREAD

**Issue by grzesw** [BenSampo/laravel-enum#15]
hi there,

any plans for next major version? i would propose following:

- use https://github.com/myclabs/php-enum - this is probably most popular enum implementation for PHP - quite heavily tested
- integrate enum fields with Eloquent models (casting attributes to enum instances)
- add ability to translate enum fields

what do you think?

**Comment by BenSampo** [comment]
Hello,

Thanks for your suggestions!

I'll definitely look into 1 & 3 and see how those might be achieved if beneficial.

Could you explain 2 in a bit more detail? A use case would be helpful in understanding what you mean.

**Comment by kminek** [comment]
something along these lines:

```
class Gender extends Enum
{
    private const MALE = 'male';
    private const FEMALE = 'female';
}

// getter
$user = User::find(1);
$user->gender->getValue() // returns Gender instance

// setter
$user->gender = Gender::MALE(); // setting instance
$user->gender = 'male'; // setting scalar value should also be accepted
```

i will be playing with the idea in my free time so i will post some implementation soon :)

**Comment by grzesw** [comment]
something along these lines:

```php
class Gender extends Enum
{
    private const MALE = 'male';
    private const FEMALE = 'female';
}

// getter
$user = User::find(1);
$user->gender->getValue() // returns Gender instance

// setter
$user->gender = Gender::MALE(); // setting instance
$user->gender = 'male'; // setting scalar value should also be accepted
```

i will be playing with the idea in my free time so i will post some implementation soon :)

**Comment by BenSampo** [comment]
@grzesw Just to let you know, I've added a section to the readme about to to do localization.

**Comment by me-shaon** [comment]
I think the current usage of this package is much better than the [php-enum](https://github.com/myclabs/php-enum). Because I have to call the Enum like a static method on `php-enum`. But it is much more intuitive to do it as in this package. For the same reason, I want to disagree with @grzesw to have the functionality to use Enums like Eloquent models. Why do we need to bloat a simple package with complicated features when it is serving the purpose just fine?
