### ISSUE TITLE
PHP 8.1 Enum

### ISSUE THREAD

**Issue by benjaminhull** [BenSampo/laravel-enum#288]
Is there any merit to having this package changed to sit on top of PHP 8.1s enum class?

Just a thought.

**Comment by BenSampo** [comment]
With the exception of bitwise enums, most of the features of this package are implemented in the core PHP enums, so I'm curious what the use case would be?

**Comment by spawnia** [comment]
There are some features we use that would be nice to have in native enums:
- descriptions
- instantiation from key strings
- randomness

Because enums do not allow inheritance, the implementation could be done through a trait that adds some useful helper functions. Maybe the addition of such functionality could smooth the transition to native enums.

**Comment by BenSampo** [comment]
Looks like https://github.com/archtechx/enums offers some of those features. I really like their meta data implementation through attributes.

**Comment by trippo** [comment]
@benjaminhull  please see also my new package [datomatic/laravel-enum-helper](https://github.com/datomatic/laravel-enum-helper)

**Comment by spawnia** [comment]
I think there are enough alternatives to this package that are based on native enums, so I don't think we should change or extend this package. I guess at some point it will become obsolete, as native enums are generally preferrable. To make the transition easier, I have added an artisan command to convert the enums of this package to native enums, see https://github.com/BenSampo/laravel-enum/pull/322.

**Comment by spawnia** [comment]
We have now added facilities to ease the migration to native PHP enums, see https://github.com/BenSampo/laravel-enum#migrate-to-native-php-enums.
