### ISSUE TITLE
Requires incorrect

### ISSUE THREAD

**Issue by joseph-bing-han** [BenSampo/laravel-enum#31]
\BenSampo\Enum\Enum::getLocalizedDescription(value): ?string
requires PHP 7.1 but you write require PHP 7.0, so I got the error message:
> In Enum.php line 100:                                             
>   Parse error: syntax error, unexpected '?'

**Comment by BenSampo** [comment]
Hi @joseph-bing-han and @me-shaon - firstly thanks both for pointing this out and for supplying the fix. I'm more than happy to merge your changes, @me-shaon, to make this package compatible with PHP 7.0 although I'd like to ensure that it does indeed work and that I don't break compatibility again in future by adding some automated testing in travis.

I currently have travis set up, but it's only testing with one environment configuration. You can see from my recent commit history (that I've since reverted) that I tried to configure travis to test in multiple environments. Unfortunately I could never get it to work for PHP 7.0. It was actually failing before ever testing the package, something to do with version mismatches when it was trying to do `composer install`. If either of you have any travis experience, it would be great if you could take a look - I'm pretty busy at the moment, so I probably wont get a change to take a look again myself for a while.

Cheers!
