### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> $enumValue ]] in class BenSampo\Enum\Enum

### ISSUE THREAD

**Issue by gustavodebiasi** [BenSampo/laravel-enum#50]
Hello Ben!

I am updating my projects to use PHP 7.3 but I found a problem that seems to be in your package.
I'm using Laravel 5.6, and your package is at 1.17.1 version.
When I tried to use Blade Inject of classes it raises a exception:

The Code:
`@inject('cstIcmsEnum', 'App\Enums\CstIcmsEnum')`

The Exception:
Unresolvable dependency resolving [Parameter #0 [ <required> $enumValue ]] in class BenSampo\Enum\Enum (View: C:\xampp\htdocs\hubdocs\resources\views\documentos\cteos.blade.php) {"userId":2,"exception":"[object] (ErrorException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> $enumValue ]] in class BenSampo\\Enum\\Enum (View: C:\\xampp\\htdocs\\hubdocs\
esources\\views\\documentos\\cteos.blade.php) at C:\\xampp\\htdocs\\hubdocs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:948, Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Unresolvable dependency resolving [Parameter #0 [ <required> $enumValue ]] in class BenSampo\\Enum\\Enum at C:\\xampp\\htdocs\\hubdocs\\vendor\\laravel\\framework\\src\\Illuminate\\Container\\Container.php:948)

If I comment the Enum Default Contructor it works fine.
```
public function __construct($enumValue)
    {
        if (!static::hasValue($enumValue)) {
            throw new InvalidEnumMemberException($enumValue, $this);
        }

        $this->value = $enumValue;
        $this->key = static::getKey($enumValue);
        $this->description = static::getDescription($enumValue);
    }
```

I search in the releases versions and found that this contructor and didn't find why this was added. 

Any advice for this issue? 
Thanks!

**Comment by BenSampo** [comment]
Hey @gustavodebiasi,

In 1.17 I introduced the ability to instantiate an enum, see the Instantiation section of the docs for details:
https://github.com/BenSampo/laravel-enum#instantiation

I think while using the @inject helper in your blade template the service container is trying to resolve and instantiate the `CstIcmsEnum` enum class. It's necessary to pass a value to the constructor in order to instantiate it, so it's throwing the error you see.

I'm guessing that you want to use the static methods on the CstIcmsEnum instead? E.g.

```php
<div>
    Enum Value: {{ \App\Enums\CstIcmsEnum::SomeKey }}
</div>
```

Or, if you don't want to reference the full path, you can add an alias in `config/app.php`:

```php
'aliases' => [
        'App' => Illuminate\Support\Facades\App::class,
        // ...
        'CstIcmsEnum' => App\Enums\CstIcmsEnum::class,
    ],
```

And access it like so:

```php
<div>
    Enum Value: {{ CstIcmsEnum::SomeKey }}
</div>
```
