### ISSUE TITLE
Attribute casting in model toArray

### ISSUE THREAD

**Issue by mdpoulter** [BenSampo/laravel-enum#86]
Hi Ben

I may be missing something, so please excuse me if I am. I've also abstracted the problem a bit using the example in the README.

I create a class such as this which uses the Enum attribute casting:

```php
class Example extends Model
{
    use CastsEnums;
    
    protected $enumCasts = [
        'user_type' => UserType::class,
    ];
}
```

After seeding, I run `Example::first()->toArray()` and it returns something like this:
```php
[
     'user_type' => 2
]
```

Whereas I expect the value to be cast and return something like this:
```php
[
     'user_type' => App\Enums\UserType{#1234
          +key: "Guest"
          +value: 2
          +description: "Guest"
        }
]
```

If I run `Example::first()->user_type`, however, the casting works perfectly.

Am I doing something wrong, or is the toArray method not supported? If it is the latter, is it possible to include support for it?

Thank you!

**Comment by atymic** [comment]
The reason you don't receive the instance is `getValue()` operates directly on the internal attributes, and returns them without using the getters/setters.

I think the current behaviour is correct, and is consistent with other object attributes (for example, dates are formatted to a string rather than returned as the object).

If it was to return the object when calling `toArray`, it would end up serialized in json, etc.

**Comment by mdpoulter** [comment]
Ah I see! That is a very good point. Thank you for clarifying 👍

**Comment by atymic** [comment]
No worries!

**Comment by kurokeita** [comment]
Hi, I'm having the same issue, take his example, I want the toArray function to return the key of the enum, not the value, how can I do that?
